name: Go
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.4'
      - name: mongo-action
        uses: DigiPie/mongo-action@v2.0.1
      - name: Install dependencies
        run: go get .
      - name: Build
        run: go build -v ./.
      - name: Test with the Go CLI with mocked data
        run: go test -v ./gifs/tests_using_custom_mocks/
      - name: Mock tests with the Go CLI using library
        run: go test -v ./gifs/mock_tests_using_library/  
      - name: Benchmark tests with the Go CLI 
        run: go test -v ./gifs/benchmark_tests
      - name: Integration tests with the Go CLI 
        run: go test -v ./gifs/integration_tests
